### PR TITLE
Implementation of Havok Havana Constraints (hk_physics - Havana)

### PR DESCRIPTION
**Pull request by CRACKbomber**
Implementation of missing functionality for various Havana constraints.

### CODE REVIEW

**Comment by int-72h** [comment]
Looking good. @melvyn2 already has some work, so maybe you could merge it to save time.

**Comment by melvyn2** [comment]
> Looking good. @melvyn2 already has some work, so maybe you could merge it to save time.

Not sure what you mean, this seems to have the commits I've already done.

**Comment by int-72h** [comment]
My bad for not being observent then.

**Comment by CRACKbomber** [comment]
A lot more work to do on the constraints and implementing missing functionality. However all the missing fragments have been partially or completely implemented. Let me know if there's any questions or comments.

**Comment by int-72h** [comment]
Good work- How far is this off relative completion/ complete enough to build on top of so we can at least launch the game, just for reference?

**Comment by melvyn2** [comment]
Thanks for all the work!

**Pull request merged**
