### PR TITLE
VPhysics Implementation/Fixes

### PR DESCRIPTION
**Pull request by CRACKbomber**
PR to handle the debugging/implementation of vphysics.

### CODE REVIEW

**Comment by CRACKbomber** [comment]
Debug/Release builds are compiling OK on Windows... Good work all...

**Comment by JusicP** [comment]
While compiling vphysics, compiler shows me weird errors such as 
error: ‘class hk_Local_Constraint_System’ has no member named ‘write_to_blueprint’.
But when i check local_constraint_system.h it does really have this member

**Comment by melvyn2** [comment]
> While compiling vphysics, compiler shows me weird errors such as
> physics_constraint.cpp:200:11: error: ‘class hk_Local_Constraint_System’ has no member named ‘write_to_blueprint’
> m_pLCS->write_to_blueprint( &bp );
> But when i check local_constraint_system.h it does really have this member
Sorry to get back to this late, but could you post the command you used to build and the full output?

**Comment by JusicP** [comment]
> > While compiling vphysics, compiler shows me weird errors such as
> > physics_constraint.cpp:200:11: error: ‘class hk_Local_Constraint_System’ has no member named ‘write_to_blueprint’
> > m_pLCS->write_to_blueprint( &bp );
> > But when i check local_constraint_system.h it does really have this member
> 
> Sorry to get back to this late, but could you post the command you used to build and the full output?

I used original tf2 leak, not team comtress 2 repo. I'll try to use this repo. Also there is modified makefile_base_posix.mak in this repo so it's maybe reason why vphysics compiles without problems.

**Comment by melvyn2** [comment]
No, the reason it compiles is that the original leak didn't have the vphysics source - this branch has a reverse engineered version of it. The makefile changes do fix some other things, but not this error.

**Comment by melvyn2** [comment]
Half a year later, these changes have been cherry-picked. Thanks for this!

**Pull request closed without merging**
